### ISSUE TITLE
Allow if-statements without a precondition

### ISSUE THREAD

**Issue by vlad2305m** [btj/proof-outline-checker#1]
```python
    assert True
    if C:
      assert C
      assert True
    else:
      assert not C
      assert True
      pass
      assert True
    assert True
```
Gives error `Kan de correctheid van deze 'if'-opdracht niet bewijzen; kan de regel voor 'if'-opdrachten niet toepassen want de preconditie van de 'then'-tak heeft niet de juiste vorm`

The current correction is:
```python
    assert True
    if C:
      assert True and C
      assert True
    else:
      assert True and not C
      assert True
      pass
      assert True
    assert True
```
which forces useless condition (`True and`) to be added to each branch. That can be simplified.

Expected fix:
add template
```python
assert True
if C:
    assert C
    ...
    assert Q
else:
    assert not C
    ...
    assert Q
assert Q
```

**Comment by btj** [comment]
I'm inclined not to implement this change, because the goal of this tool is not to enable users to prove correctness of programs as easily as possible; the goal is to teach the user the basic principles of proving program correctness. And for that, I think it is best if the checks performed by the tool are as straightforward as possible. I think it is useful if students learn the distinction between syntax and semantics, and that rigorous reasoning ultimately requires being careful about syntax.

Closing for now.
